[ADD] module: filter products in PO by vendor
odoo-ps/psus-good-minds pull request #1
Opened 2023-08-30 16:06 UTC by dkmr-odoo

### Description
The module is to filter the list of products shown in PO
to only show the products with same vendor as selected in PO.
Link to task: [3437649](https://www.odoo.com/web#id=3437649&cids=17&menu_id=4720&action=333&active_id=360&model=project.task&view_type=form)

2023-08-30 16:08 UTC, AchillesGM commented
Do I need to do anything?

Thanks,

Achilles

From: Diana Melo ***@***.***>
Date: Wednesday, August 30, 2023 at 11:07 AM
To: odoo-ps/psus-good-minds ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [odoo-ps/psus-good-minds] [ADD] module: filter products in PO by vendor (PR #1)
Description

The module is to filter the list of products shown in PO
to only show the products with same vendor as selected in PO.
Link to task: 3437649<https://www.odoo.com/web#id=3437649&cids=17&menu_id=4720&action=333&active_id=360&model=project.task&view_type=form>

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/odoo-ps/psus-good-minds/pull/1

Commit Summary

  *   49284d7<https://github.com/odoo-ps/psus-good-minds/pull/1/commits/49284d7a155a7fa9e11e074494d54e142f5d5041> Merge 14-0-group-po-deb into master
  *   fa2eb54<https://github.com/odoo-ps/psus-good-minds/pull/1/commits/fa2eb54a32c951b28e026a7d1d605288969fcd6e> Merge 14-0-group-po-deb into master
  *   c5a4e2c<https://github.com/odoo-ps/psus-good-minds/pull/1/commits/c5a4e2c96c5ea24efcb061c822232cc27f96282e> [ADD]Module: filter in PO products by vendor

File Changes

(4 files<https://github.com/odoo-ps/psus-good-minds/pull/1/files>)

  *   M goodmind_grouppo_custom/__manifest__.py<https://github.com/odoo-ps/psus-good-minds/pull/1/files#diff-3611cd8d561ab305d2e1730fa0f44742d0c4c19edfd7edd3d2e95aa7ae905247> (24)
  *   M goodmind_grouppo_custom/models/__init__.py<https://github.com/odoo-ps/psus-good-minds/pull/1/files#diff-54f6c10f3eb020b3d7ea3beec893254569ffff2cb1ca473fe31e99b537bbdfc9> (1)
  *   A goodmind_grouppo_custom/models/purchase_order_line.py<https://github.com/odoo-ps/psus-good-minds/pull/1/files#diff-e6115b6635c4c5607c0b724418fe7d9dab606e53a1026e401900255d5593f764> (16)
  *   A goodmind_grouppo_custom/views/purchase_order_views.xml<https://github.com/odoo-ps/psus-good-minds/pull/1/files#diff-1b9a751084cfdc1f29d81bbfc5e7a44450b1ad5868b5af0694f1db910d3452e2> (16)

Patch Links:

  *   https://github.com/odoo-ps/psus-good-minds/pull/1.patch
  *   https://github.com/odoo-ps/psus-good-minds/pull/1.diff

—
Reply to this email directly, view it on GitHub<https://github.com/odoo-ps/psus-good-minds/pull/1>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ATYRDR6KC4MYSLQ5IVHN6CDXX5QKPANCNFSM6AAAAAA4EYGWHY>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

2023-08-30 18:09 UTC, jefe-odoo requested changes

2023-08-30 18:10 UTC, jefe-odoo commented
 @dkmr-odoo please add a video where you show how this dev is working and add the link of this PR to the task at the bottom

2023-08-30 18:23 UTC, dkmr-odoo commented on goodmind_grouppo_custom/models/purchase_order_line.py
> +    products_with_same_vendor = fields.One2many('product.product', compute="_compute_valid_products")
This will return a list of products not the partner_ids, is it ok if I change it to product_ids?

2023-08-30 20:51 UTC, dkmr-odoo commented on goodmind_grouppo_custom/models/purchase_order_line.py
> +    def _compute_valid_products(self):
For the second bullet point, I believe the api.depends is necessary because the product list needs to be loaded according to the current vendor. Without the depends the product list in the view will only be loaded after saving the PO.

2023-08-30 23:03 UTC, jefe-odoo requested changes

2023-08-30 23:03 UTC, jefe-odoo commented on goodmind_grouppo_custom/models/purchase_order_line.py
> +    @api.depends('order_id.partner_id')
- Change api.depends by api.onchange
- use a variable for product_ids  instead a dict
- Create a new module for this development
- As we discussed it at office, attend the feedback that I give you ;)

2023-08-31 15:06 UTC, jefe-odoo commented on achilles_gentle_po_vendor_product_filter/views/purchase_order_views.xml
> +<record id="purchase_order_form_inherit_filter_by_vendor" model="ir.ui.view">
`purchase_order_form_inherit_filter_by_vendor ` -> `purchase_order_form_inherit_achilles_gentle`

2023-08-31 15:14 UTC, AchillesGM commented
We can’t access odoo is this normal?

Achilles Gentle
GoodMinds.com
519-761-0366
________________________________
From: jefe-odoo ***@***.***>
Sent: Thursday, August 31, 2023 10:06:56 AM
To: odoo-ps/psus-good-minds ***@***.***>
Cc: Achilles Gentle ***@***.***>; Comment ***@***.***>
Subject: Re: [odoo-ps/psus-good-minds] [ADD] module: filter products in PO by vendor (PR #1)


@jefe-odoo approved this pull request.

________________________________

In achilles_gentle_po_vendor_product_filter/views/purchase_order_views.xml<https://github.com/odoo-ps/psus-good-minds/pull/1#discussion_r1311780541>:

> @@ -0,0 +1,16 @@
+<?xml version="1.0" encoding="utf-8"?>
+<odoo>
+<record id="purchase_order_form_inherit_filter_by_vendor" model="ir.ui.view">


purchase_order_form_inherit_filter_by_vendor -> purchase_order_form_inherit_achilles_gentle

—
Reply to this email directly, view it on GitHub<https://github.com/odoo-ps/psus-good-minds/pull/1#pullrequestreview-1604986378>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ATYRDR7G4YGVTZKX7F4GUYDXYCSBBANCNFSM6AAAAAA4EYGWHY>.
You are receiving this because you commented.Message ID: ***@***.***>

2023-08-31 17:03 UTC, merged